/*
 * File: app/store/FolderObjectTreeStore.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ACMobileClient.store.FolderObjectTreeStore', {
    extend: 'Ext.data.TreeStore',

    requires: [
        'ACMobileClient.model.FolderObjectDataModel'
    ],

    config: {
        model: 'ACMobileClient.model.FolderObjectDataModel',
        storeId: 'FolderObjectTreeStore',
        proxy: {
            type: 'ajax',
            url: '../mobileclient_module/FolderTreeList.jsp',
            reader: {
                type: 'json',
                rootProperty: 'folders'
            }
        },
        listeners: [
            {
                fn: 'onTreestoreBeforeLoad',
                event: 'beforeload'
            }
        ]
    },

    onTreestoreBeforeLoad: function(store, operation, eOpts) {
        addSessionIdToParams(operation);

    }

});