/*
 * File: app/store/MailAttachmentStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ACMobileClient.store.MailAttachmentStore', {
    extend: 'Ext.data.Store',

    requires: [
        'ACMobileClient.model.MailAttachmentModel'
    ],

    config: {
        model: 'ACMobileClient.model.MailAttachmentModel',
        storeId: 'MailAttachmentStore',
        proxy: {
            type: 'rest',
            extraParams: {
                provider: 'mailattachment',
                properties: [
                    'id',
                    'classname',
                    'size',
                    '<mailobject>id',
                    'nameextension',
                    'displayname',
                    'previewable',
                    'textavailable'
                ]
            },
            url: '/api/rest/object',
            format: 'json',
            reader: {
                type: 'json',
                idProperty: 'id',
                rootProperty: 'data'
            }
        },
        listeners: [
            {
                fn: 'onStoreBeforeLoad',
                event: 'beforeload'
            }
        ]
    },

    onStoreBeforeLoad: function(store, operation, eOpts) {
        addSessionIdToParams(operation);

    }

});