/*
 * File: app/store/MailSearchStore.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ACMobileClient.store.MailSearchStore', {
    extend: 'Ext.data.Store',

    requires: [
        'ACMobileClient.model.MailSearchModel'
    ],

    config: {
        autoLoad: false,
        model: 'ACMobileClient.model.MailSearchModel',
        storeId: 'MailSearchStore',
        proxy: {
            type: 'ajax',
            url: 'http://212.185.58.29/roiwebui/mobileclient.app/data/mailsearch.json.jsp',
            reader: {
                type: 'json',
                rootProperty: 'data'
            }
        },
        listeners: [
            {
                fn: 'onJsonstoreBeforeLoad',
                event: 'beforeload'
            }
        ]
    },

    onJsonstoreBeforeLoad: function(store, operation, eOpts) {
        addSessionIdToParams(operation);

    }

});