/*
 * File: app/store/UserGroupSearchStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ACMobileClient.store.UserGroupSearchStore', {
    extend: 'Ext.data.Store',

    requires: [
        'ACMobileClient.model.UserGroupSearchModel'
    ],

    config: {
        model: 'ACMobileClient.model.UserGroupSearchModel',
        storeId: 'UserSearchStore',
        proxy: {
            type: 'rest',
            extraParams: {
                provider: 'usergroupsearch',
                properties: [
                    'id',
                    'fullname',
                    'name',
                    'classname',
                    'objectvisible'
                ],
                sort: [
                    Ext.encode({
                        direction: 'ASC',
                        property: 'name'
                    })
                ],
                parameters: Ext.encode({
                    prefixSort: true,
                    prefixKey: 'name'
                })
            },
            url: '/api/rest/object',
            format: 'json',
            reader: {
                type: 'json',
                rootProperty: 'data'
            }
        },
        listeners: [
            {
                fn: 'onJsonstoreBeforeLoad',
                event: 'beforeload'
            }
        ]
    },

    onJsonstoreBeforeLoad: function(store, operation, eOpts) {
        addSessionIdToParams(operation);

    }

});