/*
 * File: app/view/ImageViewerContainer.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ACMobileClient.view.ImageViewerContainer', {
    extend: 'Ext.Container',

    config: {
        layout: {
            type: 'fit'
        }
    },

    showLoader: function() {
        this.setMasked({ 
            xtype: 'loadmask', 
            message: 'loading' 
        });

    },

    viewerHidden: function() {
        this.imageViewer.viewerHidden();
    },

    viewerShown: function() {
        this.imageViewer.viewerShown(true);
    },

    hideLoader: function() {
        this.setMasked(false);

    }

});