/*
 * File: app/view/LoginPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ACMobileClient.view.LoginPanel', {
    extend: 'Ext.Panel',

    requires:[
        'ACMobileClient.store.RootFolderStore'
    ],

    config: {
        cls: 'logoBack',
        fullscreen: true,
        itemId: 'loginPanel',
        id: 'loginPanel',
        items: [
            {
                xtype: 'formpanel',
                centered: true,
                height: 400,
                itemId: 'loginForm',
                id: 'loginForm',
                minHeight: 330,
                padding: 7,
                showAnimation: 'slideIn',
                cls: 'login_panel',
                style: 'background-color:transparent;box-shadow:none;',
                width: 300,
                url: '/api/rest/session/login',
                items: [
                    {
                        xtype: 'image',
                        cls: 'dslogo',
                        height: 41,
                        docked:'top',
                        src: 'images/gds2-logo.png'
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        title: 'Login'
                    },
                    {
                        xtype: 'fieldset',
                        itemId: 'loginFieldSet',
                        width: 250,
                        margin: '0.5em auto 1.5em',
                        items: [
                            {
                                xtype: 'textfield',
                                border: '',
                                itemId: 'userName',
                                id: 'userName',
                                width: '',
                                label: 'Username:',
                                labelWidth: 100,
                                name: 'username'
                            },
                            {
                                xtype: 'passwordfield',
                                itemId: 'passWord',
                                id: 'passWord',
                                label: 'Password:',
                                labelWidth: 100,
                                name: 'password'
                            },
                            {
                                xtype: 'checkboxfield',
                                itemId: 'rememberLogin',
                                label: 'Remember Me:',
                                labelWidth: 180,
                                name: 'rememberLogin'
                            }
                        ]
                    },
                    {
                        xtype: 'button',
                        id: 'loginButton',
                        itemId: 'loginButton',
                        ui: 'action-round',
                        width: 150,
                        text: 'Login',
                        margin: '0 auto'
                    },
                    {
                        xtype: 'button',
                        itemId: 'forgotPwdBtn',
                        id: 'forgotPwdBtn',
                        //ui: 'action-round',
                        //width: 150,
                        text: 'Forgot Password',
                        cls: 'btn-forgot-pwd'
                        //margin: '0 auto'
                    },
                    {
                        xtype: 'button',
                        itemId: 'desktopBtn',
                        id: 'desktopBtn',
                        //ui: 'action-round',
                        //width: 150,
                        text: 'Desktop Version',
                        cls: 'btn-forgot-pwd'
                        //margin: '0 auto'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onUserNameAction',
                event: 'action',
                delegate: '#userName'
            },
            {
                fn: 'onPanelPainted',
                event: 'painted'
            }
        ]
    },

    onUserNameAction: function(textfield, e, eOpts) {
        this.down('#passWord').focus();
    },

    onPanelPainted: function(element, eOpts) {
        var checkBoxItem = this.down('#rememberLogin'),
            deviceEvent = 'click';
        if (ACUtils.utils.isAutoLogin()) {
            this.down('#userName').setValue(ACUtils.utils.getUserName());
            this.down('#passWord').setValue(ACUtils.utils.getPassWord());
            this.down('#rememberLogin').check();
            //this.doLogin();
            this.fireEvent('autoLogin');
        } else {
            if(navigator.platform === 'BlackBerry'){
                if(Ext.os.deviceType === 'Phone'){
                    deviceEvent = 'touchup';
                }
                document.getElementById(checkBoxItem.getId()).addEventListener(deviceEvent,function(){
                    if(checkBoxItem.isChecked()){
                        checkBoxItem.uncheck();
                    } else {
                        checkBoxItem.check();
                    }
                });
            }
        }
    }

});