/*
 * File: app/view/LogoContainer.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ACMobileClient.view.LogoContainer', {
    extend: 'Ext.Container',

    config: {
        cls: 'logoBack',
        listeners: [
            {
                fn: 'onContainerPainted',
                event: 'painted'
            },
            {
                fn: 'onContainerShow',
                event: 'show'
            }
        ]
    },

    onContainerPainted: function(component, eOpts) {

    },

    onContainerShow: function(component, eOpts) {

    }

});