/*
 * File: app/view/MainPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ACMobileClient.view.MainPanel', {
    extend: 'Ext.Panel',

    config: {
        cls: 'page',
        padding: 0,
        style: '',
        styleHtmlContent: true,
        ui: 'light',
        hideOnMaskTap: false,
        layout: {
            type: 'card'
        },
        tpl: [
            '<h2>Test</h2>',
            'blablabla'
        ],
        listeners: [
            {
                fn: 'onPanelShow',
                event: 'show'
            },
            {
                fn: 'onContentContainerAdd',
                event: 'add',
                delegate: '#contentContainer'
            }
        ],
        items: [
            {
                xtype: 'container',
                itemId: 'contentContainer',
                style: 'font-size:1.25em',
                ui: 'light',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'container',
                        itemId: 'content',
                        layout: {
                            animation: 'slide',
                            type: 'card'
                        }
                    }
                ]
            }
        ]
    },

    onPanelShow: function(component, eOpts) {
        var me = this, men = null, contentContainer, logoContainer;

        MyGlobals.mainPanel = me;

        //create the menu panel
        if (MyGlobals.isPhone) {
            men = Ext.create("ACMobileClient.view.MenuPanel", {});
        }
        else {
            men = Ext.create("ACMobileClient.view.MenuPanel", {
                modal: true,
                hideOnMaskTap: true
            });
        }
        men.internInit();

        //remember the panel in the globals to reuse it on another place
        MyGlobals.menuPanel = men;    
        me.add(men);

        men.navigateToFolder('', "Start", true, this.down('#documentsBar'));
        men.navigateToFolder('', "Start", true, this.down('#sharedFolders'));

        if (MyGlobals.isPhone) {
            men.setStyle("font-size:1.25em");
            me.setActiveItem(men);
        }

        //register event for orientation change
        Ext.Viewport.on('orientationchange', 'handleOrientationChange', me,  {buffer: 50 });

        //get the preview container
        contentContainer = me.down('#contentContainer');
        MyGlobals.contentContainer = contentContainer;

        if (!MyGlobals.isPhone) {
            logoContainer = Ext.create("ACMobileClient.view.LogoContainer", {});
            logoContainer.persistent = true;
            MyGlobals.lastObjectInContentContainer = logoContainer;
            me.loadContentContainer(logoContainer, true, false, "Start");
            //contentContainer.down('#content').add(logoContainer);
        }

        //end preview module init

        //init the view
        me.handleOrientationChange();

        me.showMenuPanel();

        me.loadQuickSearchAreas();

    },

    onContentContainerAdd: function(container, item, index, eOpts) {
        this.down('#contentContainer').setMasked(false);
    },

    contentContainerBack: function() {
        var cont = MyGlobals.contentContainer.down('#content'),
            lastObj = MyGlobals.lastObjectInContentContainer,
            items;

        //MyGlobals.contentContainer.remove(MyGlobals.lastObjectInContentContainer, false);

        cont.getLayout().setAnimation({
            type: 'slide',
            direction: 'right'
        });


        items = cont.items;
        MyGlobals.lastObjectInContentContainer = cont.getAt(items.length - 2);

        if (items.length === 1 && MyGlobals.isPhone) {
            this.showMenuPanel();

            setTimeout(function() {
                cont.remove(cont.getActiveItem(), true);
            }, 1000);    


            MyGlobals.menuPanel.deselectAllLists();
        }
        else {
            cont.remove(cont.getActiveItem(), true);
            if (items.length > 1) {
                if (items.length === 2) {
                    if (MyGlobals.menuPanel) {
                        MyGlobals.menuPanel.deselectAllLists();
                    }
                }
                cont.setActiveItem(items.length-2);
            }
        }
    },

    handleObject: function(classObject, objectId, name, persistent, record) {
        var me = this,
            tab;
        ACUtils.utils.checkConnectionWithFunction(function() {
            var previewAble = record.get("previewable"),
                textAvailable = record.get("textavailable"),
                isFolder = record.get("isfolder");

            if (classObject==="mailobject") {
                me.showMail(objectId, persistent);
            }
            else if (previewAble) {
                me.showPreview(objectId,1,persistent);
            }
            else if (textAvailable) {
                me.showText(objectId,persistent);
            }
            else if (isFolder) {
                tab = MyGlobals.menuPanel.down('#tabPanel').getActiveItem();
                //MyGlobals.menuPanel.down('#tabPanel').setActiveItem(me.down('#documentsBar'));

                MyGlobals.menuPanel.navigateToFolder(objectId, name, false, tab);
            }
            else {
                Ext.Msg.alert('Error', 'Für dieses Objekt ist derzeit noch keine Anzeige erstellt: '+classObject, Ext.emptyFn);   
            }

        });
    },

    handleOrientationChange: function() {
        var me = this;
        ACUtils.utils.checkConnectionWithFunction(function() {
            //alert("Orient change: "+Ext.Viewport.getOrientation());

            var men = MyGlobals.menuPanel,
                isAndroidTablet = false,
                cont = me.down('#content'),
                items = cont.items,
                itemLen = items.length,
                height, i, el;

            //var listButton = me.down('#listButton');
            //var backButton = me.down('#backButton');
            //men.hide();

            if (Ext.os.deviceType === 'Tablet' && !Ext.os.is.iOS) {
                isAndroidTablet = true;
            }


            if (MyGlobals.isPhone) {
                //men.show();
                //backButton.show();
                //listButton.hide();
                MyGlobals.showListButton = false;
            }
            else if ((Ext.Viewport.getOrientation() === 'portrait' && !isAndroidTablet) || (Ext.Viewport.getOrientation() !== 'portrait' && isAndroidTablet)) {
                height = me.element.getHeight();
                men.setDocked(null);
                men.setTop(5);
                men.setLeft(5);
                men.setHeight(height-70);
                men.setWidth(315);
                //men.setStyle(null);
                men.removeCls("MenuBorder");
                men.hide();

                //this.down("#toolbarRight").setStyle("font-size: 1.25em;");

                //listButton.show();
                MyGlobals.showListButton = true;
                //backButton.hide();
            }
            else {
                men.setDocked("left");
                men.setTop(null);
                men.setLeft(null);
                //men.setStyle("border-right: 1px solid #000 !important;");
                men.setCls("MenuBorder");
                men.setHeight(null);
                men.setWidth(315);

                //this.down("#toolbarRight").setStyle("font-size: 1.25em;");
                men.show();
                //listButton.hide();
                MyGlobals.showListButton = false;
                //backButton.hide();
            }

            if (MyGlobals.imageViewer) {
                MyGlobals.imageViewer.reloadViewer();
            }

            //reload content elements
            for (i=0; i<itemLen; i+=1) {
                el = cont.getAt(i);
                if (el.doRepaint) {
                    el.doRepaint();
                }
            }
            me.restoreSidePanel();
            Ext.repaint();
        });
    },

    hideInfoPanel: function() {
        var items = this.getInnerItems();
        this.getLayout().setAnimation({
            type: 'slide',
            direction: 'right'
        });

        this.setActiveItem(items.length-2);
        //is remove, when info is shown next time
        //this.remove(MyGlobals.infoPanel, true);    

    },

    hideLoader: function() {
        this.down('#contentContainer').setMasked(false);
    },

    loadContentContainer: function(container, persistent, hasPrevious, navTitle) {
        var cont = MyGlobals.contentContainer.down('#content'),
            lastObj = MyGlobals.lastObjectInContentContainer,
            items = cont.items,
            itemLen = items.length,
            contCon;

        if (!persistent && lastObj !== null && !lastObj.persistent) {
            itemLen-=1;
            setTimeout(function() {
                console.log("removing last: "+lastObj);
                cont.remove(lastObj, true);
            }, 1000);
        }

        if (cont.getLayout && cont.getLayout().setAnimation) {
            cont.getLayout().setAnimation({
                type: 'slide',
                direction: 'left'
            });
        }

        contCon = Ext.create('ACMobileClient.view.ContentContainer', {});
        contCon.hasPrevious = hasPrevious;
        if (hasPrevious) {
            if (itemLen > 0) {
                contCon.navTitle =  cont.getAt(itemLen-1).prevNavTitle;
            }
        }

        contCon.persistent = container.persistent;
        contCon.add(container);


        //MyGlobals.contentContainer.remove(MyGlobals.lastObjectInContentContainer, false);
        cont.add(contCon);
        cont.setActiveItem(contCon);
        contCon.prevNavTitle = navTitle;
        MyGlobals.lastObjectInContentContainer = contCon;
        this.showInContentContainer();

        //hide menu panel when showing something in container
        setTimeout(function() {
            var men;
            if (MyGlobals.showListButton)  {
                men = MyGlobals.menuPanel;
                men.deselectAllLists();
                men.hide();
            }
        }, 20);

    },

    loadLanguage: function() {

    },

    loadQuickSearchAreas: function() {
        var theOr = '';

        MyGlobals.areaIds = '';

        Ext.Ajax.request({
            url: '/api/rest/object.json',
            method: 'get',
            params: { 
                sessionId: MyGlobals.sessionId,
                provider: 'area',
                source: 'MAIN_MODULE_MANAGEMENT/mobileclient/control/areas',
                page: 1,
                start: 0,
                limit: 2000,
                noCache: new Date().getTime()
            },
            success: function(response) {
                var jsonResp = Ext.decode(response.responseText),
                    areas = jsonResp.data,
                    i;
                for (i = 0; i < areas.length; i+=1) {
                    MyGlobals.areaIds += theOr + "inpath:" + areas[i].id;
                    theOr = " OR ";
                }
            },
            failure: function() {
            },
            scope: this
        });
    },

    loadNextPage: function() {
        if (MyGlobals.imageViewer.pageCount > MyGlobals.imageViewer.pageNumber) {
            this.showPreview(MyGlobals.imageViewer.objectId,  MyGlobals.imageViewer.pageNumber+1);
        }
    },

    loadPrevPage: function() {
        if (MyGlobals.imageViewer.pageNumber > 1) {
            this.showPreview(MyGlobals.imageViewer.objectId,  MyGlobals.imageViewer.pageNumber-1);
        }
    },

    restoreSidePanel: function() {
        var iPanel, height, width;
        if (MyGlobals.infoPanel) {
            if (!MyGlobals.isPhone) {
                iPanel = MyGlobals.infoPanel;
                height = this.element.getHeight();
                width = this.down('#contentContainer').element.getWidth();
                iPanel.setDocked(null);
                iPanel.setShowAnimation("slideIn");
                iPanel.setHideAnimation({
                    type: 'slideOut',
                    direction: 'right'
                });
                iPanel.setTop(0);
                iPanel.setLeft(width-320);
                iPanel.setHeight(height);
                iPanel.setWidth(320);

                //iPanel.showBy(button);
            }
        }


    },

    showInContentContainer: function() {
        if (MyGlobals.isPhone) {

            //MyGlobals.contentContainer.setShowAnimation("slideIn");
            this.getLayout().setAnimation({
                type: 'slide',
                direction: 'left'
            });

            this.setActiveItem(MyGlobals.contentContainer);
        }
    },

    showInfoPanel: function(button) {
        var me = this,
            iPanel = Ext.create('ACMobileClient.view.InfoPanel', {}),
            height;

        me.add(iPanel);
        iPanel.hide();

        if (MyGlobals.isPhone) {
            me.getLayout().setAnimation({
                type: 'slide',
                direction: 'left'
            });
            me.setActiveItem(iPanel);    
        }
        else {
            height = me.element.getHeight();
            iPanel.setDocked(null);
            iPanel.setTop(5);
            iPanel.setLeft(5);
            iPanel.setHeight(height-80);
            iPanel.setWidth(315);

            iPanel.showBy(button);
        }

        MyGlobals.infoPanel = iPanel;

    },

    showInfoPanelSlided: function(objectId, noteId, className) {
        var me = this,
            iPanel;

        if (MyGlobals.infoPanel) {
            //MyGlobals.infoPanel.hide();
            me.remove(MyGlobals.infoPanel, true);
            MyGlobals.infoPanel = null;
        }

        iPanel = Ext.create('ACMobileClient.view.InfoPanel', {});
        iPanel.load(objectId);


        if (className && className === 'noteobject') {
            //switch not note view
            iPanel.showNote(noteId);
        }

        me.add(iPanel);
        iPanel.hide();

        iPanel.loadCallback = function() {
            var height, width;

            if (MyGlobals.isPhone) {
                me.getLayout().setAnimation({
                    type: 'slide',
                    direction: 'left'
                });
                me.setActiveItem(iPanel);    
            }
            else {
                height = me.element.getHeight();
                width = me.down('#contentContainer').element.getWidth();
                iPanel.setDocked(null);
                iPanel.setShowAnimation("slideIn");
                iPanel.setHideAnimation({
                    type: 'slideOut',
                    direction: 'right'
                });
                iPanel.setTop(0);
                iPanel.setLeft(width-320);
                iPanel.setHeight(height);
                iPanel.setWidth(320);
                iPanel.addCls('shadowPanel');

                //iPanel.showBy(button);
                iPanel.show();
            }
        };

        MyGlobals.infoPanel = iPanel;

    },

    showLoader: function() {
        this.down('#contentContainer').setMasked({ 
            xtype: 'loadmask', 
            message: 'loading' 
        });
    },

    showMail: function(objectId, persistent) {
        var me = this;
        ACUtils.utils.checkConnectionWithFunction(function() {
            var mailView = Ext.create("ACMobileClient.view.MailViewContainer", {});
            mailView.load(objectId);
            me.loadContentContainer(mailView,persistent,true,"Mail");
        });
    },

    showMenuPanel: function() {
        if (MyGlobals.isPhone) {
            //MyGlobals.menuPanel.down("#documentList").deselectAll();

            //Reverse the slide direction before using setActiveItem()
            this.getLayout().setAnimation({
                type: 'slide',
                direction: 'right'
            });
            this.setActiveItem(MyGlobals.menuPanel);
        }
    },

    showPreview: function(objectId, page, persistent) {
        var me = this;
        ACUtils.utils.checkConnectionWithFunction(function() {
            //precreate a preview container
            var previewContainer = Ext.create("ACMobileClient.view.PreviewContainer", {});
            MyGlobals.previewContrainer = previewContainer;
            previewContainer.down('#previewCarousel').loadPreview(objectId, page, previewContainer);

            me.loadContentContainer(previewContainer,persistent,true,"Document");
        });
    },

    showText: function(objectId, persistent) {
        var me = this;
        ACUtils.utils.checkConnectionWithFunction(function() {
            var textView = Ext.create("ACMobileClient.view.TextViewContainer", {});
            textView.load(objectId);
            me.loadContentContainer(textView,persistent,true,"Document");
        });
    },

    switchToRoot: function(obj) {
        //reset to root
        //remove all other items
        var me = obj,
            toRemove = me.getInnerItems().slice(1);

        console.log("switch to root");

        me.getLayout().setAnimation({
            type: 'slide',
            direction: 'right'
        });

        me.setActiveItem(0);
        setTimeout(function() {
            toRemove.forEach(function (el) {
                me.remove(el, true);
            });
        }, 500);

    }

});