/*
 * File: app/view/NoteEntry.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ACMobileClient.view.NoteEntry', {
    extend: 'Ext.form.FieldSet',
    alias: 'widget.noteEntry',

    config: {
    },

    loadNote: function(item, noteId) {
        if (noteId && noteId == item.get('id')) {
            this.addCls("selectedNote");
        }
        var content = item.get('content');
        content =  content.replace(/\n/gi, "<br>");
        var html = '<div class="notesHead">'+
        '<div class="notesUser">'+item.get('creator')+'</div>'+
        '<div class="notesDate">'+formatDate(item.get('createdate'))+'</div>'+
        '</div><div class="notesText">'+content+'</div>';


        this.add({
            xtype: 'label',
            html: html,
            flex: 0
        });

    }

});