/*
 * File: app/view/PreviewContainer.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ACMobileClient.view.PreviewContainer', {
    extend: 'Ext.Container',

    requires: [
        'ACMobileClient.view.PreviewCarousel'
    ],

    config: {
        itemId: '',
        margin: 0,
        padding: 0,
        ui: 'light',
        layout: {
            type: 'hbox'
        },
        items: [
            {
                xtype: 'container',
                height: 40,
                itemId: 'labeFrame',
                left: 14,
                style: 'background:#ddd;opacity:0.5;',
                top: 20,
                width: 60,
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'label',
                        centered: true,
                        html: '1/2',
                        itemId: 'pageLabel',
                        ui: 'dark'
                    }
                ]
            },
            {
                xtype: 'mycarousel',
                itemId: 'previewCarousel',
                flex: 1
            }
        ]
    },

    setPageLabel: function(page, pageCount) {
        this.down('#pageLabel').setHtml(page+"/"+pageCount);

    }

});