/*
 * File: app/view/ReceiverField.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ACMobileClient.view.ReceiverField', {
    extend: 'Ext.Button',
    alias: 'widget.ReceiverField',

    config: {
        margin: '0 5 0 0',
        maxWidth: 125,
        style: 'display:inline-block;top:-2px',
        ui: 'small',
        text: 'test@test.de',
        listeners: [
            {
                fn: 'onButtonTap',
                event: 'tap'
            },
            {
                fn: 'onButtonInitialize',
                event: 'initialize'
            }
        ]
    },

    onButtonTap: function(button, e, eOpts) {
        this.theParent.selectField(this);
    },

    onButtonInitialize: function(component, eOpts) {
        this.value = this.config.value;
        this.text = this.config.html;
    }

});