/*
 * File: app/view/SearchContainer.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ACMobileClient.view.SearchContainer', {
    extend: 'Ext.Container',
    alias: 'widget.searchcontainer',

    requires: [
        'ACMobileClient.view.SearchContainerSub'
    ],

    config: {
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'SearchContainerSub',
                itemId: 'searchContainerSub'
            }
        ],
        listeners: [
            {
                fn: 'onContainerActivate',
                event: 'activate'
            },
            {
                fn: 'onContainerDeactivate',
                event: 'deactivate'
            }
        ]
    },

    onContainerActivate: function(newActiveItem, container, oldActiveItem, eOpts) {
        var ai = this.getActiveItem();
        if (ai.activateCallback) {
            ai.activateCallback();
        }
    },

    onContainerDeactivate: function(oldActiveItem, container, newActiveItem, eOpts) {
        var ai = this.getActiveItem();
        if (ai.deactivateCallback) {
            ai.deactivateCallback();
        }
    },

    doubleTapCallback: function() {
        MyGlobals.mainPanel.switchToRoot(this);


    }

});