/*
 * File: app/view/UploadQueueContainer.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ACMobileClient.view.UploadQueueContainer', {
    extend: 'Ext.Container',
    alias: 'widget.uploadqueue',

    config: {
        iconCls: 'list',
        title: 'Uploads',
        hidden: false,
        itemId: 'Uploads',
        padding: 10,
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Uploads',
                layout: {
                    align: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            this.up('uploadqueue').fireEvent('cancel');
                        },
                        itemId: 'Cancel',
                        text: 'Cancel'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            this.up('uploadqueue').fireEvent('start');
                        },
                        itemId: 'Start',
                        text: 'Start'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            this.up('uploadqueue').fireEvent('stop');
                        },
                        hidden: true,
                        itemId: 'Stop',
                        text: 'Stop'
                    }
                ]
            },
            {
                xtype: 'list',
                itemId: 'Queue',
                mode: 'SIMPLE',
                itemTpl: [
                    '<div class="list_style">',
                    '    <div class="list_icons">',
                    '        <div class="list_icon upload_status{status}"></div>',
                    '    </div>',
                    '    <div class="list_entry">{name}</div>',
                    '    <div class="list_entry">{percent}%<span class="msg">{message}</span></div>',
                    '</div>'
                ],
                store: 'UploadQueue'
            }
        ]
    }

});