/*
 * File: app/view/UploadQueueContainer.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ACMobileClient.view.UploadQueueContainer', {
    extend: 'Ext.Container',
    alias: 'widget.uploadqueue',

    config: {
        title: 'Uploads',
        iconCls: 'list',
        hidden: false,
        itemId: 'Uploads',
        padding: 10,
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Uploads',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            this.up('uploadqueue').fireEvent('cancel');
                        },
                        itemId: 'Cancel',
                        text: 'Cancel'
                    }
                ]
            },
            {
                xtype: 'list',
                itemId: 'Queue',
                itemTpl: [
                    '<div>List Item {string}</div>'
                ]
            }
        ]
    }

});