/*
 * File: app/model/AreaDataModel.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ACMobileClient.model.AreaDataModel', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                convert: function(v, rec) {
                    var trans = ACMobileClient.Messages['area.'+v];
                    if (trans) {
                        return trans;
                    }
                    else {
                        return v;
                    }

                },
                mapping: 'text',
                name: 'name',
                type: 'string'
            },
            {
                name: 'id',
                type: 'int'
            },
            {
                convert: function(v, rec) {
                    return 'folderobject';
                },
                name: 'classname'
            },
            {
                convert: function(v, rec) {
                    return true;
                },
                name: 'read',
                type: 'boolean'
            },
            {
                convert: function(v, rec) {
                    return false;
                },
                name: 'previewable',
                type: 'boolean'
            },
            {
                convert: function(v, rec) {
                    return false;
                },
                name: 'previewable',
                type: 'boolean'
            },
            {
                convert: function(v, rec) {
                    return true;
                },
                name: 'isfolder',
                type: 'boolean'
            }
        ]
    }
});