/*
 * File: app/model/MailViewModel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ACMobileClient.model.MailViewModel', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                name: 'id',
                type: 'string'
            },
            {
                name: 'subject',
                type: 'string'
            },
            {
                mapping: 'htmlbody',
                name: 'text',
                type: 'string'
            },
            {
                name: 'answered',
                type: 'boolean'
            },
            {
                name: 'flagged',
                type: 'boolean'
            },
            {
                name: 'draft',
                type: 'boolean'
            },
            {
                name: 'deleted',
                type: 'boolean'
            },
            {
                name: 'seen',
                type: 'boolean'
            },
            {
                mapping: 'fromaddress',
                name: 'from',
                type: 'string'
            },
            {
                name: 'priority',
                type: 'string'
            },
            {
                name: 'priority',
                type: 'string'
            },
            {
                mapping: 'toaddress',
                name: 'to',
                type: 'auto'
            },
            {
                mapping: 'ccaddress',
                name: 'cc',
                type: 'auto'
            },
            {
                mapping: 'bccaddress',
                name: 'bcc',
                type: 'auto'
            },
            {
                mapping: 'rfc822date',
                name: 'mailDate',
                type: 'date'
            },
            {
                name: 'attachments',
                type: 'auto'
            }
        ]
    }
});