/*
 * File: app/model/ObjectInfoModel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ACMobileClient.model.ObjectInfoModel', {
    extend: 'Ext.data.Model',
    alias: 'model.ObjectInfoModel',

    config: {
        fields: [
            {
                name: 'id',
                type: 'int'
            },
            {
                convert: function(v, rec) {
                    var objTextKey = rec.get('objecttextkey'),
                        trans;

                    if (objTextKey && objTextKey !== "") {
                        trans = ACMobileClient.Messages[objTextKey];
                        if (trans) {
                            return trans;
                        }
                    }
                    return v;

                },
                mapping: 'displayname',
                name: 'name',
                type: 'string'
            },
            {
                name: 'objecttextkey',
                type: 'string'
            },
            {
                name: 'description',
                type: 'string'
            },
            {
                mapping: '["creator.fullname"]',
                name: 'creator',
                type: 'string'
            },
            {
                mapping: '["lastmodifier.fullname"]',
                name: 'lastmodifier',
                type: 'string'
            },
            {
                mapping: '["owner.fullname"]',
                name: 'owner',
                type: 'string'
            },
            {
                name: 'createdate',
                type: 'date'
            },
            {
                name: 'lastmodifydate',
                type: 'date'
            },
            {
                name: 'updatedate',
                type: 'date'
            }
        ]
    }
});