/*
 * File: app/model/QuickSearchDataModel.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ACMobileClient.model.QuickSearchDataModel', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                convert: function(v, rec) {
                    var trans = ACMobileClient.Messages['quicksearch.'+v];
                    if (trans) {
                        return trans;
                    }
                    else {
                        return v;
                    }

                },
                mapping: 'text',
                name: 'label'
            },
            {
                mapping: 'query',
                name: 'value',
                type: 'string'
            }
        ]
    }
});