/*
 * File: app/model/UserGroupSearchModel.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ACMobileClient.model.UserGroupSearchModel', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                name: 'id'
            },
            {
                mapping: 'id',
                name: 'value'
            },
            {
                name: 'name'
            },
            {
                defaultValue: true,
                name: 'objectvisible',
                type: 'boolean'
            },
            {
                name: 'fullname'
            },
            {
                name: 'classname'
            },
            {
                convert: function(v, rec) {
                    if (rec.get("fullname") != null) {
                        return rec.get("fullname");
                    }
                    else {
                        return rec.get("name");
                    }
                },
                name: 'text'
            }
        ]
    }
});