/*
 * File: app/view/MyFormPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ACMobile.view.MyFormPanel', {
    extend: 'Ext.form.Panel',

    requires: [
        'ACMobile.view.SearchInputField'
    ],

    config: {
        cls: 'whiteForm',
        padding: 0,
        layout: {
            type: 'vbox'
        },
        items: [
            {
                xtype: 'SearchInputField',
                itemId: 'toField'
            },
            {
                xtype: 'textareafield',
                itemId: 'bodyText'
            },
            {
                xtype: 'container',
                flex: 1,
                minHeight: 100
            }
        ],
        listeners: [
            {
                fn: 'onBodyTextFocus',
                event: 'focus',
                delegate: '#bodyText'
            }
        ]
    },

    onBodyTextFocus: function(textfield, e, eOpts) {

    }

});